CREATE DATABASE IF NOT EXISTS shortener DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_bin;
USE shortener;
CREATE TABLE IF NOT EXISTS short_url (
    id       BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    code     VARCHAR(16)  NOT NULL,
    long_url VARCHAR(8192) NOT NULL,
    UNIQUE KEY idx_code (code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
